### ISSUE TITLE
Kotlin starter pack won't work on macOS

### ISSUE THREAD

**Issue by Karloid** [HaliteChallenge/Halite-III#131]
Nothing changed in starter pack, just downloaded and unzipped [https://halite.io/assets/downloads/Halite3_Kotlin_MacOS.zip](https://halite.io/assets/downloads/Halite3_Kotlin_MacOS.zip)

macOS 10.13.6

```
$ kotlinc -version
info: kotlinc-jvm 1.2.60 (JRE 1.8.0_121-b13)

$ java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

$ ./run_game.sh
[info] Map seed is 1541271599
[info] [P0] Launching with command java MyBot
[info] [P1] Launching with command java MyBot
[info] [P0] Initializing player
[info] [P1] Initializing player
[error] [P0] Failed to initialize
[error] [P0] Player's error output was:
[error] [P0] Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
[error] [P0]    at MyBot.main(MyBot.kt)
[error] [P0] Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
[error] [P0]    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[error] [P0]    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] [P0]    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
[error] [P0]    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error] [P0]    ... 1 more
[warn] [P0] Killing player
[error] [P1] Failed to initialize
[error] [P1] Player's error output was:
[error] [P1] Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
[error] [P1]    at MyBot.main(MyBot.kt)
[error] [P1] Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
[error] [P1]    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[error] [P1]    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] [P1]    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
[error] [P1]    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error] [P1]    ... 1 more
[warn] [P1] Killing player
[info] Player initialization complete
[info] [1] [P0] player has insufficient resources to continue
[info] [1] [P1] player has insufficient resources to continue
[info] [1] Game has ended
[info] Opening a file at replays/replay-20181103-215959+0300-1541271599-32-32.hlt
[info] Player 0, '(failed to initialize)', was rank 2 with 0 halite
[info] Player 1, '(failed to initialize)', was rank 1 with 0 halite
[info] [P0] Player has log output. Writing a log at replays/errorlog-20181103-215959+0300-1541271599-32-32-0.log
[info] [P1] Player has log output. Writing a log at replays/errorlog-20181103-215959+0300-1541271599-32-32-1.log
```

**Comment by Karloid** [comment]
For my self I fixed that issue by compiling via kotlinc to jar and then sending that jar to halite

**Comment by Karloid** [comment]
Adding kotlin runtime to runtime doesn't make trick for me, most probably I screwed something somewhere :)

**Comment by lidavidm** [comment]
Glad it worked. For server-side, the plan is also to use kotlinc to make a JAR to avoid this issue. We still have to get Kotlin actually installed, though.

**Comment by lidavidm** [comment]
Forgot to follow up here, but this is fixed server-side; client side you should have Kotlin build a JAR: `kotlinc --include-runtime` (or configure IntelliJ).
